<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://it.univaq.incipict.ems/cdShm"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	name="cdShm"
	targetNamespace="http://it.univaq.incipict.ems/cdShm">

  <wsdl:types>
    <xsd:schema targetNamespace="http://it.univaq.incipict.ems/cdShm">
    	<xsd:element name="prepareRequest" type="xsd:string"/>
    </xsd:schema>
  </wsdl:types>

  <wsdl:message name="prepareRequest">
    <wsdl:part element="tns:prepareRequest" name="request"/>
  </wsdl:message>
 
  <wsdl:portType name="cdShmPT">
  	<wsdl:operation name="Prepare">
      <wsdl:input message="tns:prepareRequest"/>
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="cdShmBinding" type="tns:cdShmPT">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Prepare">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="cdShmService">
    <wsdl:port binding="tns:cdShmBinding" name="cdShmPort">
      <soap:address location="http://localhost:8080/ode/processes/cdShm"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
