<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions
	targetNamespace="http://it.univaq.incipict.ems/cdEp/Artifacts"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:client="http://it.univaq.incipict.ems/cdEp"
	xmlns:ep="http://it.univaq.incipict.ems/ep"
	xmlns:crowding="http://it.univaq.incipict.ems/crowding"
	xmlns:civilprotection="http://it.univaq.incipict.ems/civilprotection">
  
  <partnerLinkType name="ClientPLT" xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <role name="Client" portType="client:cdEpPT"/>
  </partnerLinkType> 
  
  <partnerLinkType name="EpPLT" xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <role name="Ep" portType="ep:epPT"/>
  </partnerLinkType>

  <partnerLinkType name="EpConsumerPLT" xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <role name="EpConsumer" portType="ep:epConsumerPT"/>
  </partnerLinkType>

  <partnerLinkType name="CrowdingPLT" xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <role name="Crowding" portType="crowding:crowdingPT"/>
  </partnerLinkType>

  <partnerLinkType name="CivilProtectionPLT" xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <role name="CivilProtection" portType="civilprotection:CivilProtectionPT"/>
  </partnerLinkType>

  <import location="cdEp.wsdl" namespace="http://it.univaq.incipict.ems/cdEp"/>
  <import location="ep.wsdl" namespace="http://it.univaq.incipict.ems/ep"/>
  <import location="crowding.wsdl" namespace="http://it.univaq.incipict.ems/crowding"/>
  <import location="civilprotection.wsdl" namespace="http://it.univaq.incipict.ems/civilprotection"/>
</definitions>
